Repository OCA/l10n-germany, pull requests merged in 2025-09, with the labels that each got.

#194 [17.0][IMP] datev_export_xml: Add some length constrains to fix possible errors en export
  datev_export_xml/views/templates.xml
Labels: bot is merging ⏳

#198 [18.0][MIG] l10n_de_location_nuts
  l10n_de_location_nuts/README.rst
  l10n_de_location_nuts/__init__.py
  l10n_de_location_nuts/__manifest__.py
  l10n_de_location_nuts/hooks.py
  l10n_de_location_nuts/i18n/es.po
  l10n_de_location_nuts/i18n/l10n_de_location_nuts.pot
  l10n_de_location_nuts/pyproject.toml
  l10n_de_location_nuts/readme/CONFIGURE.md
  l10n_de_location_nuts/readme/CONTRIBUTORS.md
  l10n_de_location_nuts/readme/DESCRIPTION.md
  l10n_de_location_nuts/readme/USAGE.md
  l10n_de_location_nuts/static/description/icon.png
  l10n_de_location_nuts/static/description/index.html
  l10n_de_location_nuts/wizard/__init__.py
  l10n_de_location_nuts/wizard/nuts_import.py
Labels: approved, bot is merging ⏳

#200 [17.0][FIX] l10n_de_tax_statement: views to use column_invisible attribute and remove setup files
  l10n_de_tax_statement/views/l10n_de_tax_statement_view.xml
  setup/l10n_de_tax_statement/odoo/addons/l10n_de_tax_statement
  setup/l10n_de_tax_statement/setup.py
Labels: approved
